name: Deploy

on: 
  push: # 在 push 时 
    branches: master # 且 为 master 分支
    paths: src/* # 且 仅当 src 目录下文件变动

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1 # 检出
    - name: install # 安装
      run: yarn
    - name: lint # lint 检测
      run: yarn lint
    - name: build # build 打包
      run: yarn build
    - name: depoy # 部署
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} # 密钥
          PUBLISH_BRANCH: gh-pages # 分支
          PUBLISH_DIR: ./dist # 文件输出路径
